# Generated by Django 3.2.20 on 2023-10-08 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('story_test', '0002_auto_20231008_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='next_story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='story_test.story'),
        ),
        migrations.AlterField(
            model_name='story',
            name='choices_available',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='story_test.choice'),
        ),
    ]
