# Generated by Django 4.2.5 on 2023-10-13 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_test', '0005_alter_story_choices_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='object_needed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
